### PR TITLE
bug/fix USCPI failure

### LINKED ISSUE #42: Fix USCPI API failure due to date mismatch
The USCPI liquidator and disputer bots, fail erratically due to a date mismatch issue.

For some reason, when the API call is made the current date for the server is 17th June 2023, but the St louis API server has a current date of 16th June 2023. Due to this, the API call fails with the error _"Bad Request.  Variable realtime_end can not be after today's date (2023-06-16) unless it's equal to the real-time max date 9999-12-31."_

[This](https://api.stlouisfed.org/fred/series/observations?&file_type=json&api_key=6a4b9077e53414238274b3294d45dcfc&series_id=CPIAUCSL&observation_start=2023-04-18&realtime_end=2023-06-17) is the API call that was failing 

Below is the last error we faced. The error was triggered at 7:33AM IST and was resolved at around 10:30 AM IST (i.e. when st louis time changed to 12PM 17th June 2023) 

Error

> USCPI_Liquidator_Disputer_Bots
> APP  [7:33 AM](https://global-access-labs.slack.com/archives/C05AL5TEGUV/p1686967428761919)
> [error] cUSCPI Liqudiator (Liquidator#index)⭢Liquidator execution error:rotating_light:
> • error: Error: :rotating_light:Could not parse price result from url https://api.stlouisfed.org/fred/series/observations?&file_type=json&api_key=6a4b9077e53414238274b3294d45dcfc&series_id=CPIAUCSL&observation_start=2023-04-18&realtime_end=2023-06-17: {"error_code":400,"error_message":"Bad Request.  Variable realtime_end can not be after today's date (2023-06-16) unless it's equal to the real-time max date 9999-12-31."}
>    at StLouisFedGovPriceFeed._getHistoricalPrice (/home/ubuntu/bots-startup/uma-protocol/packages/financial-templates-lib/dist/price-feed/StLouisFedGovPriceFeed.js:120:19)
>    at runMicrotasks (<anonymous>)
>    at processTicksAndRejections (internal/process/task_queues.js:95:5)
>    at async StLouisFedGovPriceFeed.update (/home/ubuntu/bots-startup/uma-protocol/packages/financial-templates-lib/dist/price-feed/StLouisFedGovPriceFeed.js:62:29)
>    at async Promise.all (index 2)
>    at async Liquidator.update (/home/ubuntu/bots-startup/uma-protocol/packages/liquidator/src/liquidator.js:194:5)
>    at async retry.retries (/home/ubuntu/bots-startup/uma-protocol/packages/liquidator/index.js:328:11)
>    at async run (/home/ubuntu/bots-startup/uma-protocol/packages/liquidator/index.js:325:7)
>    at async Poll (/home/ubuntu/bots-startup/uma-protocol/packages/liquidator/index.js:444:5)

> [error] cUSCPI Disputer (Disputer#index)⭢Disputer execution error:rotating_light:
> • error: Error: :rotating_light:Could not parse price result from url https://api.stlouisfed.org/fred/series/observations?&file_type=json&api_key=6a4b9077e53414238274b3294d45dcfc&series_id=CPIAUCSL&observation_start=2023-04-18&realtime_end=2023-06-17: {"error_code":400,"error_message":"Bad Request.  Variable realtime_end can not be after today's date (2023-06-16) unless it's equal to the real-time max date 9999-12-31."}
>    at StLouisFedGovPriceFeed._getHistoricalPrice (/home/ubuntu/bots-startup/uma-protocol/packages/financial-templates-lib/dist/price-feed/StLouisFedGovPriceFeed.js:120:19)
>    at runMicrotasks (<anonymous>)
>    at processTicksAndRejections (internal/process/task_queues.js:95:5)
>    at async StLouisFedGovPriceFeed.update (/home/ubuntu/bots-startup/uma-protocol/packages/financial-templates-lib/dist/price-feed/StLouisFedGovPriceFeed.js:62:29)
>    at async Promise.all (index 2)
>    at async Disputer.update (/home/ubuntu/bots-startup/uma-protocol/packages/disputer/src/disputer.js:115:5)
>    at async retry.retries (/home/ubuntu/bots-startup/uma-protocol/packages/disputer/index.js:252:11)
>    at async run (/home/ubuntu/bots-startup/uma-protocol/packages/disputer/index.js:250:7)
>    at async Poll (/home/ubuntu/bots-startup/uma-protocol/packages/disputer/index.js:344:5)

### PR DESCRIPTION
**Pull request by RojhatToptamus**
Uses St Louis local time to retrieve the current price of USCPI.

Fixes #42

### CODE REVIEW

File: packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts [hunk 1]
```diff
@@ -45,6 +48,14 @@ export class StLouisFedGovPriceFeed extends PriceFeedInterface {
...
+    const date = new Date();
+    const options = {
+      timeZone: timeZone,
+    };
+    const timestamp = date.toLocaleString('en-US', options);
+    return Math.round(new Date(timestamp).getTime() / 1000);
+  };
 
   public async update(ancillaryData?: string): Promise<void> {
     const currentTime = await this.getTime();
```
Comment (KohliSuraj) [inline packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts:67]: this would be a more appropriate place to get the current time depending on boolean `this.useStLouisLocalTime`

File: packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts [hunk 2]
```diff
@@ -68,10 +79,15 @@ export class StLouisFedGovPriceFeed extends PriceFeedInterface {
...
-    this.currentPrice = await this._getHistoricalPrice(currentTime);
-    this.lastUpdateTime = currentTime;
+    if (this.useStLouisLocalTime) {
+      const stLouisTime = this.getTimestampInTimeZone('America/Chicago');  // St Louis uses America/Chicago timezone.
+      this.currentPrice = await this._getHistoricalPrice(stLouisTime);     // use stLouis time to retrieve price.
+    }
+    else {
+      this.currentPrice = await this._getHistoricalPrice(currentTime)
+    }
+    this.lastUpdateTime = currentTime;  // make sure that the last update time always reflects the bot time in any case.
```
Comment (KohliSuraj) [inline packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts:89]: `this.lastUpdateTime = currentTime;` will always store bot time, which is incorrect. Once we make the above change, it should store either bot time or st louis time, depending on boolean.

File: packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts
Comment (KohliSuraj) [inline packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts:1]: I think we should change `getHistoricalPrice` function as well. so that it uses correct time depending on `this. useStLouisLocalTime`

**Review by KohliSuraj — CHANGES_REQUESTED** [review]

File: packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts (hunk 2 above)
Comment (RojhatToptamus) [reply packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts:89]: Using current time for **lastUpdated** ensures accurate calculation of **historicalLookbackWindow**.

File: packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts
Comment (RojhatToptamus) [reply packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts:1]: Updated **_getHistoricalPrice** function as per the suggestion.

File: packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts [hunk 3]
```diff
@@ -46,6 +49,20 @@ export class StLouisFedGovPriceFeed extends PriceFeedInterface {
     };
   }
 
+  public getTimestampInTimeZone = (timeZone: string) => {
```
Comment (KohliSuraj) [inline packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts:52]: In this function, we are dividing the time by 1000 i.e. converting ms to seconds, right?

but, in `getTimeDifferenceInSeconds` function we are subtracting stLouisTime (i.e. in seconds) from machineTime (i.e. in milliseconds)

@RojhatToptamus This looks incorrect to me?

**Review by KohliSuraj — CHANGES_REQUESTED** [review]

File: packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts (hunk 3 above)
Comment (RojhatToptamus) [reply packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts:52]: Both values are in seconds. The function below is passed as an argument to the constructor and used to obtain machine time.

`const getTime = () => Math.round(new Date().getTime() / 1000);`

Comment (KohliSuraj) [reply packages/financial-templates-lib/src/price-feed/StLouisFedGovPriceFeed.ts:52]: Got it, thanks for explaining!

**Review by KohliSuraj — APPROVED** [review]
@RojhatToptamus Thanks for intense testing on this one!
